########################  client 和 server 都用到的公共配置  ################################
name: "elgongRPC-config"

# 编解码协议： 目前支持两种, 选其中一种
codecPlugin: "gobCodec"
# codecPlugin: "msgpackCodec"


# 传输协议插件
protocolPlugin: "defaultProtocol"

#######################  server 需要的配置  ################################
# 服务端使用的配置
# 指定要监听的端口
server:
    ip: 192.168.43.123
    port: 8999


###################### client 需要的配置  ################################
# 连接池相关
# 连接池插件
connPlugin: "defaultConnPool"
conn:
    # 初始化连接数，目前时懒加载，因为我懒
    initialCap: 10
    # 最大连接数
    maxCap: 100
    # 最大空闲连接
    maxIdle: 10
    # 是否开启掉线自动重连
    failReconnect: true
    # 重连超时时长
    failReconnectSecond: 5
    # 重连尝试次数
    failReconnectTime: 1
    # 是否开启定时任务-健康管理默认开启
    isTickerOpen: true
    # 健康管理定时时长
    tickerTime: 5
    # 建立 tcp 连接 超时时长
    timeout: 3

# 手动录入服务部署机器的IP 列表
services:
    # 服务名：[ip, ip...]
    MyService : ["192.168.43.123:8999"]
    NoUseService : ["0.0.0.0:8990"]

# 负载均衡插件
selectorPlugin: "defaultSelector"

# 服务注册插件
#  使用该插件，需要服务端函数导入，执行初始化哈  _ "github.com/elgong/elgongRPC/soa/register/redisPlugin"
registerPlugin: "redisRegisterPlugin"  # 需要和服务发现redis 一起使用

# 服务发现插件
#discoveyPlugin: "defaultDiscovey"
discoveyPlugin: "redisDiscoveyPlugin"






